DROP TABLE IF EXISTS CLIENT CASCADE;
CREATE TABLE CLIENT (
ID INT AUTO_INCREMENT PRIMARY KEY,
BRAND_ID INT NOT NULL,
START_DATE TIMESTAMP NOT NULL,
END_DATE TIMESTAMP NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY INT NOT NULL,
PRICE DOUBLE NOT NULL,
CURR VARCHAR (5) NOT NULL
);

DROP TABLE IF EXISTS BRANDS CASCADE;
CREATE TABLE BRANDS (
BRAND_ID INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR (8) NOT NULL
);

ALTER TABLE CLIENT
ADD FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(BRAND_ID);